update func on top

diff --git a/src/secureboot b/src/secureboot
--- a/src/secureboot
+++ b/src/secureboot
@@ -2,57 +2,7 @@
 
 set -euo pipefail
 
-SB_CONFIG_FILE="/etc/secureboot.conf"
-
-
-if [ -r "$SB_CONFIG_FILE" ]; then
-  . "$SB_CONFIG_FILE"
-else
-  echo "Failed to read the secureboot configuration file '$SB_CONFIG_FILE'"
-  exit 1
-fi
-
-mkdir -p "$UEFI_KEYS_DIR"
-
-while getopts ":gesvlh" opt; do
-  case "$opt" in
-    g)
-      generate_uefi_keys;
-      ;;
-    e)
-      enroll_uefi_keys;
-      ;;
-    s)
-      sign_uefi_keys;
-      ;;
-    v)
-      verify_signatures;
-      ;;
-    l)
-      list_uefi_keys;
-      ;;
-    h)
-      echo
-      echo " -g  : Generate the UEFI Secure Boot keys"
-      echo " -e  : Enrolling secure boot keys in UEFI firmware"
-      echo " -s  : Signing the boot loader with secure boot keys"
-      echo " -v  : Verify the signed boot loader"
-      echo " -l  : List all the secure boot keys enrolled in firmware"
-      exit 0
-      ;;
-    \?)
-      printf '%s\n' "ERROR: Invalid option: '$OPTARG'" >&2
-      echo
-      echo " -g  : Generate the UEFI Secure Boot keys"
-      echo " -e  : Enrolling secure boot keys in UEFI firmware"
-      echo " -s  : Signing the boot loader with secure boot keys"
-      echo " -v  : Verify the signed boot loader"
-      echo " -l  : List all the secure boot keys enrolled in firmware"
-      exit 1
-      ;;
-  esac
-done
-
+## Functions
 
 generate_uefi_keys() {
   cd "$UEFI_KEYS_DIR"
@@ -122,3 +72,56 @@ list_uefi_keys() {
   echo "Listing the secure boot keys enrolled in firmware"
   efi-readvar
 }
+
+## Main
+
+SB_CONFIG_FILE="/etc/secureboot.conf"
+
+
+if [ -r "$SB_CONFIG_FILE" ]; then
+  . "$SB_CONFIG_FILE"
+else
+  echo "Failed to read the secureboot configuration file '$SB_CONFIG_FILE'"
+  exit 1
+fi
+
+mkdir -p "$UEFI_KEYS_DIR"
+
+while getopts ":gesvlh" opt; do
+  case "$opt" in
+    g)
+      generate_uefi_keys;
+      ;;
+    e)
+      enroll_uefi_keys;
+      ;;
+    s)
+      sign_uefi_keys;
+      ;;
+    v)
+      verify_signatures;
+      ;;
+    l)
+      list_uefi_keys;
+      ;;
+    h)
+      echo
+      echo " -g  : Generate the UEFI Secure Boot keys"
+      echo " -e  : Enrolling secure boot keys in UEFI firmware"
+      echo " -s  : Signing the boot loader with secure boot keys"
+      echo " -v  : Verify the signed boot loader"
+      echo " -l  : List all the secure boot keys enrolled in firmware"
+      exit 0
+      ;;
+    \?)
+      printf '%s\n' "ERROR: Invalid option: '$OPTARG'" >&2
+      echo
+      echo " -g  : Generate the UEFI Secure Boot keys"
+      echo " -e  : Enrolling secure boot keys in UEFI firmware"
+      echo " -s  : Signing the boot loader with secure boot keys"
+      echo " -v  : Verify the signed boot loader"
+      echo " -l  : List all the secure boot keys enrolled in firmware"
+      exit 1
+      ;;
+  esac
+done
